apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: countdowns.stable.dwk
spec:
  group: stable.dwk
  scope: Namespaced
  names:
    kind: CountDown
    singular: countdown
    plural: countdowns
    shortNames:
      - cd
      - cdown
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                length:
                  type: integer
                delay:
                  type: integer
                image:
                  type: string
      additionalPrinterColumns:
        - name: Length
          description: Length of the countdown
          jsonPath: .spec.length
          type: integer

        - name: Delay
          description: Length of time (ms) between executions
          jsonPath: .spec.delay
          type: integer
