apiVersion: v1
kind: Service
metadata:
  name: dummy-svc

spec:
  type: NodePort
  selector:
    stage: "v0.3"
  ports:
    - name: http
      nodePort: 30090
      port: 1234
      protocol: TCP
      targetPort: 3000
