apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-pv

spec:
  storageClassName: standard
  capacity:
    storage: 620Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-prod-agent-1
