apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  labels:
    version: "v1.2.1"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
        - name: logger-container
          image: akhonya/logger:v1.2.1
          imagePullPolicy: IfNotPresent
