apiVersion: apps/v1
kind: Deployment
metadata:
  name: loger-dep-main
  namespace: project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
        
    spec:
      containers:
        - name: logger
          image: akhonya/logger:v1.2.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE
                  name: logger-config
      volumes:
        - name: config-volume
          configMap:
            name: logger-config
