apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingong
          image: akhonya/pingpong:v1.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: db-configmap
