apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-full-dep

spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger

    spec:
      containers:
        - name: writter
          image: akhonya/writter:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /var/log/

        - name: reader
          image: akhonya/reader:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: logs
              mountPath: /var/log/

      volumes:
        - name: logs
          emptyDir: {}
