apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: project
  annotations:
    app.kubernetes.io/owner: itsfoss

spec:
  ports:
    - port: 6379
      name: data

  clusterIP: None
  selector:
    app: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-stset
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
